# Generated by Django 3.0 on 2020-08-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Image',
            new_name='image',
        ),
    ]
