# Generated by Django 3.0 on 2020-08-15 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
