# Generated by Django 3.0 on 2020-08-12 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200812_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
