# Generated by Django 3.0 on 2020-08-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_retweet_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_comment',
        ),
        migrations.DeleteModel(
            name='RETweeT',
        ),
    ]
