# Generated by Django 3.0 on 2020-08-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20200812_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.Tweet'),
        ),
    ]
