# Generated by Django 3.0 on 2020-08-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweet_retweeted_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.BooleanField(default=False),
        ),
    ]
